version: '3.5'

services:


    revproxy:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on:
        - frontend
        - backend

    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: tietokanta
        POSTGRES_PASSWORD: salasana
      container_name: db_postgres

    frontend:
      image: frontexample
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost/api
        
    backend:
      image: backexample
      ports:
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost
        - REDIS=redissrv
        - REDIS_PORT=6379
        - DB_USERNAME=tietokanta
        - DB_PASSWORD=salasana
        - DB_HOST=db
      depends_on:
        - db
        
    redissrv:
      image: redis
      ports:
        - 6379:6379
