version: '3.5'

services:

    frontend:
      image: frontexample
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000
        
    backend:
      image: backexample
      ports:
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redissrv
        - REDIS_PORT=6379
        
    redissrv:
      image: redis
      ports:
        - 6379:6379
